// ============================================================
// BATTLE ECHOES — artifacts/data.ts
// Dane artefaktów — 6 na bitwę, 4 rzadkości
// ============================================================

export type Rarity = 'common' | 'uncommon' | 'rare' | 'legendary';
export type ArtifactCategory = 'weapon' | 'armor' | 'document' | 'personal';

export interface Artifact {
  id:          string;
  battleId:    string;
  name:        string;
  category:    ArtifactCategory;
  rarity:      Rarity;
  icon:        string;
  description: string;       // krótki opis
  lore:        string;       // dłuższy tekst historyczny
  unlockCondition: string;   // jak odblokować
  unlockedBy:  'listen' | 'listen_all' | 'visit_gps' | 'complete';
  xpReward:    number;
  coinReward:  number;
}

// ── Konfiguracja rzadkości ────────────────────────────────
export const RARITY_META: Record<Rarity, {
  label: string; color: string; glow: string; chance: string;
}> = {
  common:    { label: 'Pospolity',    color: '#94a3b8', glow: 'rgba(148,163,184,0.3)', chance: '60%' },
  uncommon:  { label: 'Niezwykły',   color: '#4ade80', glow: 'rgba(74,222,128,0.3)',  chance: '25%' },
  rare:      { label: 'Rzadki',      color: '#60a5fa', glow: 'rgba(96,165,250,0.3)',  chance: '12%' },
  legendary: { label: 'Legendarny',  color: '#D4A017', glow: 'rgba(212,160,23,0.4)',  chance: '3%'  },
};

// ── Artefakty Grunwald 1410 ───────────────────────────────
const GRUNWALD_ARTIFACTS: Artifact[] = [
  {
    id: 'grunwald_sword_common',
    battleId: 'grunwald-1410',
    name: 'Miecz Piechura',
    category: 'weapon',
    rarity: 'common',
    icon: '⚔',
    description: 'Prosty miecz żołnierza pieszego z bitwy pod Grunwaldem.',
    lore: 'Tysiące takich mieczy leżały po bitwie na polach Grunwaldu. Wykonane z żelaza, bez ozdób — narzędzia zwykłych ludzi wciągniętych w wielką historię. Archeolodzy do dziś odnajdują fragmenty podobnych ostrzy w okolicznych polach.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'grunwald_shield_uncommon',
    battleId: 'grunwald-1410',
    name: 'Tarcza z Krzyżem',
    category: 'armor',
    rarity: 'uncommon',
    icon: '🛡',
    description: 'Tarcza krzyżacka porzucona w panicznej ucieczce.',
    lore: 'Czarny krzyż na białym tle — symbol, który przez wieki budził trwogę w Prusach i Polsce. Po Grunwaldzie wiele takich tarcz zdobili Polacy jako trofea wojenne. Chorągwie krzyżackie złożono u stóp Jagiełły — symbol klęski Zakonu.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'grunwald_letter_rare',
    battleId: 'grunwald-1410',
    name: 'List Jagiełły',
    category: 'document',
    rarity: 'rare',
    icon: '📜',
    description: 'Kopia listu króla Władysława do kapituły krakowskiej.',
    lore: 'Po zwycięstwie Jagiełło pisał do Krakowa z wiadomością o klęsce Zakonu. "Wielki Mistrz z wieloma komturami poległ" — donosił król. List dotarł do Krakowa 18 lipca, wywołując spontaniczne świętowanie. Oryginał przechowywany jest w Archiwum Głównym Akt Dawnych w Warszawie.',
    unlockCondition: 'Odsłuchaj wszystkie 4 perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'grunwald_helmet_uncommon',
    battleId: 'grunwald-1410',
    name: 'Hełm Rycerski',
    category: 'armor',
    rarity: 'uncommon',
    icon: '⛑',
    description: 'Żelazny hełm z przyłbicą — standard rycerza XV wieku.',
    lore: 'Rycerze obu stron nosili podobne hełmy z opuszczaną przyłbicą. W letnim upale bitwy pod Grunwaldem, w pełnej zbroi płytowej, temperatura wewnątrz hełmu mogła przekraczać 50 stopni. Wielu rycerzy ginęło nie od miecza, ale z wyczerpania i udaru.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'grunwald_banner_rare',
    battleId: 'grunwald-1410',
    name: 'Chorągiew Ziemi Krakowskiej',
    category: 'personal',
    rarity: 'rare',
    icon: '🚩',
    description: 'Replika jednej z 91 chorągwi polskich pod Grunwaldem.',
    lore: '91 chorągwi polskich, 40 litewskich i tatarskich, setki rot pieszych — Grunwald był kolektywnym wysiłkiem całej Europy Środkowej. Chorągiew Ziemi Krakowskiej z białym orłem na czerwonym tle walczyła w centrum szyku. Jan Długosz opisał każdą chorągiew w swojej kronice.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 100, coinReward: 35,
  },
  {
    id: 'grunwald_sword_jungingen',
    battleId: 'grunwald-1410',
    name: 'Miecz von Jungingena',
    category: 'weapon',
    rarity: 'legendary',
    icon: '🗡',
    description: 'Legendarny miecz Wielkiego Mistrza Ulricha von Jungingena.',
    lore: 'Ulrich von Jungingen — Wielki Mistrz Zakonu Krzyżackiego — poległ na polu bitwy pod Grunwaldem, co było wydarzeniem bez precedensu. Jego śmierć oznaczała koniec epoki. Według przekazów walczył do ostatniego momentu, odrzucając propozycje ucieczki. Gdzie dokładnie poległ — historycy spierają się do dziś. Dotarcie na pole bitwy GPS odblokowuje ten artefakt.',
    unlockCondition: 'Odwiedź pole bitwy w Grunwaldzie (GPS)',
    unlockedBy: 'visit_gps',
    xpReward: 300, coinReward: 100,
  },
];

// ── Artefakty Ypres 1914 ──────────────────────────────────
const YPRES_ARTIFACTS: Artifact[] = [
  {
    id: 'ypres_helmet_common',
    battleId: 'ypres-1914',
    name: 'Hełm Stalowy Mk I',
    category: 'armor',
    rarity: 'common',
    icon: '🪖',
    description: 'Stalowy hełm brytyjskiego żołnierza z 1914 roku.',
    lore: 'W 1914 roku żołnierze wciąż walczyli w tradycyjnych kapeluszach lub czapkach. Stalowe hełmy wprowadzono dopiero w 1915 roku po ogromnych stratach od odłamków artyleryjskich. Ten prosty kawałek stali uratował tysiące żyć.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'ypres_letter_uncommon',
    battleId: 'ypres-1914',
    name: 'List z Frontu',
    category: 'document',
    rarity: 'uncommon',
    icon: '✉',
    description: 'List szeregowego żołnierza do rodziny — nigdy nie wysłany.',
    lore: 'Miliony takich listów pisano w okopach Flandrii. Żołnierze pisali o tęsknocie za domem, o błocie i zimnie okopów, rzadko o prawdziwym horrorze walki — cenzura wojskowa usuwała zbyt szczere opisy. Ten list znaleziono przy ciele żołnierza z Somerset Regiment w 1919 roku.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'ypres_rifle_uncommon',
    battleId: 'ypres-1914',
    name: 'Karabin Lee-Enfield',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '🔫',
    description: 'Standardowy karabin brytyjskiej piechoty.',
    lore: 'Żołnierze brytyjscy słynęli z "szybkiego ognia" — 15 celnych strzałów na minutę z Lee-Enfielda. Niemcy w pierwszych tygodniach wierzyli, że Brytyjczycy mają karabiny maszynowe. To mistrzostwo w obsłudze broni uratowało BEF pod Mons i Ypres.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'ypres_map_rare',
    battleId: 'ypres-1914',
    name: 'Mapa Okopów',
    category: 'document',
    rarity: 'rare',
    icon: '🗺',
    description: 'Oryginalna mapa sztabowa linii okopów pod Ypres.',
    lore: 'System okopów pod Ypres rozciągał się na setki kilometrów. Mapy sztabowe były ściśle tajne — schwytany żołnierz z mapą narażał cały front. Ta mapa pochodzi z archiwum Imperial War Museum w Londynie i pokazuje pozycje z listopada 1914 — ostatni dzień pierwszej bitwy.',
    unlockCondition: 'Odsłuchaj wszystkie 4 perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'ypres_poppy_rare',
    battleId: 'ypres-1914',
    name: 'Mak Flandryjski',
    category: 'personal',
    rarity: 'rare',
    icon: '🌺',
    description: 'Symbol pamięci — mak rosnący na polach Flandrii.',
    lore: 'Po bitwach 1914-1918 pola Flandrii pokryły się makami — kwiaty rosły na rozkopanej, wapiennej ziemi pełnej prochów żołnierzy. Wiersz "In Flanders Fields" z 1915 roku uczynił mak symbolem pamięci o poległych. Do dziś Brytyjczycy noszą sztuczne maki w okolicach 11 listopada.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'ypres_menin_gate',
    battleId: 'ypres-1914',
    name: 'Fragment Bramy Menin',
    category: 'personal',
    rarity: 'legendary',
    icon: '🏛',
    description: 'Cegiełka symbolizująca 54 896 poległych bez grobu.',
    lore: 'Brama Menin w Ypres nosi 54 896 imion żołnierzy Wspólnoty Brytyjskiej poległych we Flandrii, których ciał nigdy nie odnaleziono. Co wieczór o 20:00, nieprzerwanie od 1928 roku (z wyjątkiem okupacji 1940-1944), trębacze grają Last Post. Tradycja trwa do dziś. Odwiedź Ypres aby zobaczyć to na żywo.',
    unlockCondition: 'Odwiedź Ypres GPS',
    unlockedBy: 'visit_gps',
    xpReward: 300, coinReward: 100,
  },
];

// ── Artefakty Waterloo 1815 ───────────────────────────────
const WATERLOO_ARTIFACTS: Artifact[] = [
  {
    id: 'waterloo_musket_common',
    battleId: 'waterloo-1815',
    name: 'Muszkiet Piechoty',
    category: 'weapon',
    rarity: 'common',
    icon: '🔫',
    description: 'Standardowy muszkiet z epoki napoleońskiej.',
    lore: 'Muszkiety skałkowe były niedokładne i wolne w ładowaniu — 3 strzały na minutę to był rekord. Dlatego piechota walczyła w zwartych szeregach: salwy z setek karabinów jednocześnie były śmiertelne nawet przy słabej celności.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'waterloo_eagle_legendary',
    battleId: 'waterloo-1815',
    name: 'Orzeł Napoleoński',
    category: 'personal',
    rarity: 'legendary',
    icon: '🦅',
    description: 'Symbol pułku — zdobyty Orzeł Napoleoński.',
    lore: 'Orły napoleońskie były świętością pułków — utrata orła to hańba, zdobycie cudzego — chwała. Pod Waterloo Brytyjczycy zdobyli dwa orły. Kapitan Clark z Royal Dragoons schwytał orła 105. pułku liniowego w trakcie szarży. Zdobyte orły były prezentowane królowi. Ten symbol napoleońskiej potęgi dziś strzeże w Tower of London.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Waterloo',
    unlockedBy: 'complete',
    xpReward: 400, coinReward: 150,
  },
  {
    id: 'waterloo_letter_uncommon',
    battleId: 'waterloo-1815',
    name: 'Biuletyn Wellingtona',
    category: 'document',
    rarity: 'uncommon',
    icon: '📋',
    description: 'Oficjalny raport Wellingtona po zwycięstwie.',
    lore: 'Wellington pisał swój słynny "biuletyn z Waterloo" niemal bezpośrednio po walce, w nocy z 18 na 19 czerwca. "Nigdy nie byłem tak blisko klęski" — podobno powiedział po bitwie. Raport był suchy i rzeczowy, ale to właśnie ten dokument ogłosił Europie koniec epoki napoleońskiej.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'waterloo_cuirass_rare',
    battleId: 'waterloo-1815',
    name: 'Kirys Kawalerzysty',
    category: 'armor',
    rarity: 'rare',
    icon: '🛡',
    description: 'Napierśnik ciężkiej kawalerii — ostatnia zbroja w historii.',
    lore: 'Kiryśnicy — ciężka kawaleria w stalowych napierśnikach — byli ostatnimi rycerzami w historii wojen europejskich. Pod Waterloo szarżowali wielokrotnie na brytyjskie czworoboki, za każdym razem z ogromnymi stratami. Ich napierśniki chroniły przed muszkietem z daleka, ale z bliska były bezużyteczne.',
    unlockCondition: 'Odsłuchaj wszystkie 4 perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'waterloo_shako_uncommon',
    battleId: 'waterloo-1815',
    name: 'Czako Grenadiera',
    category: 'armor',
    rarity: 'uncommon',
    icon: '🎩',
    description: 'Wysoka czapka grenadiera Starej Gwardii.',
    lore: 'Stara Gwardia Napoleona — najlepsi żołnierze Europy — szarżowała pod Waterloo jako ostatnia nadzieja. Gdy zostali odparci przez Brytyjczyków, w armii napoleońskiej rozległ się okrzyk: "La Garde recule!" — Gwardia się cofa! To zdanie oznaczało koniec bitwy i koniec cesarstwa.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'waterloo_coin_common',
    battleId: 'waterloo-1815',
    name: 'Moneta z 1815 roku',
    category: 'personal',
    rarity: 'common',
    icon: '🪙',
    description: 'Srebrna moneta z okresu Stu Dni Napoleona.',
    lore: 'Monety bite podczas Stu Dni (marzec–czerwiec 1815) są dziś niezwykłą rzadkością. Na awersie profil Napoleona — cesarza który wrócił z Elby. Na rewersie orzeł. Przez sto dni żołnierze płacili tymi monetami za chleb i wino, nie wiedząc że to ostatnie tygodnie cesarstwa.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
];

// ── Artefakty Verdun 1916 ─────────────────────────────────
const VERDUN_ARTIFACTS: Artifact[] = [
  {
    id: 'verdun_dog_tag_common',
    battleId: 'verdun-1916',
    name: 'Nieśmiertelnik Żołnierza',
    category: 'personal',
    rarity: 'common',
    icon: '🪪',
    description: 'Blaszka identyfikacyjna żołnierza z bitwy pod Verdun.',
    lore: 'Pod Verdun walczyło ponad 70 milionów pocisków przez 10 miesięcy. Identyfikacja poległych była często niemożliwa — ciała rozrywane przez artylerię. Nieśmiertelniki były jedyną szansą na przywrócenie tożsamości. Ossarium w Douaumont przechowuje kości 130 000 niezidentyfikowanych żołnierzy.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'verdun_gas_mask_uncommon',
    battleId: 'verdun-1916',
    name: 'Maska Gazowa M2',
    category: 'armor',
    rarity: 'uncommon',
    icon: '😷',
    description: 'Francuska maska gazowa — ochrona przed fosgenim.',
    lore: 'Pod Verdun Niemcy użyli fosgen — gaz 18 razy bardziej trujący od chloru, bezwonny i niewidoczny. Żołnierze ginęli nie czując zagrożenia. Maska M2 była ratunkiem — ale wymagała perfekcyjnego uszczelnienia. Jeden oddech bez maski mógł oznaczać powolną śmierć przez obrzęk płuc.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'verdun_bayonet_uncommon',
    battleId: 'verdun-1916',
    name: 'Bagnet Lebel 1886',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '🗡',
    description: 'Igłowy bagnet karabinu Lebel — symbol walki okopowej.',
    lore: 'W tunelach i okopach pod Verdun walczono na bagnety i łopaty. Karabin był za długi, granaty za niebezpieczne w ciasnych przestrzeniach. Bagnet Lebel z charakterystycznym igłowym ostrzem był bronią ostatniej szansy. Tranchée des Baïonnettes — okop bagnetów — jest do dziś miejscem pamięci.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'verdun_medal_rare',
    battleId: 'verdun-1916',
    name: 'Medal Verdun',
    category: 'personal',
    rarity: 'rare',
    icon: '🥇',
    description: 'Medal ustanowiony dla uczestników obrony Verdun.',
    lore: 'Rotacja przez Verdun była celową polityką francuską — prawie cała armia przeszła przez to piekło. "On ne passe pas" — Nie przejdą — stało się hasłem obrony. Medal Verdun przyznano 650 000 żołnierzy. Był symbolem wyjątkowego poświęcenia w najtragiczniejszej bitwie I Wojny.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'verdun_helmet_rare',
    battleId: 'verdun-1916',
    name: 'Hełm Adrian M15',
    category: 'armor',
    rarity: 'rare',
    icon: '⛑',
    description: 'Stalowy hełm Adrian — symbol żołnierza francuskiego.',
    lore: 'Hełm Adrian, wprowadzony w 1915 roku, uratował tysiące żyć pod Verdun. Przed jego wprowadzeniem ranny w głowę żołnierz miał 80% szans na śmierć. Po — tylko 40%. Charakterystyczny grzebień na szczycie pozwalał spływać wodzie. Pod Verdun ziemia wchłonęła tyle krwi, że gleba do dziś jest toksyczna.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'verdun_ossuary_fragment',
    battleId: 'verdun-1916',
    name: 'Kamień z Ossarium',
    category: 'personal',
    rarity: 'legendary',
    icon: '🏛',
    description: 'Symbol Ossarium Douaumont — grobowca 130 000 nieznanych.',
    lore: 'Ossarium w Douaumont to największy grób zbiorowy we Francji. W kostnicach za szklanymi panelami można zobaczyć kości 130 000 żołnierzy — nieznanych, niemożliwych do identyfikacji. Co roku 11 listopada prezydenci Francji i Niemiec spotykają się tu w geście pojednania. Verdun stało się symbolem absurdu wojny.',
    unlockCondition: 'Odwiedź pole bitwy pod Verdun (GPS)',
    unlockedBy: 'visit_gps',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Termopile 480 p.n.e. ───────────────────────
const THERMOPYLAE_ARTIFACTS: Artifact[] = [
  {
    id: 'thermopylae_spear_common',
    battleId: 'thermopylae-480bc',
    name: 'Dory — Włócznia Hoplity',
    category: 'weapon',
    rarity: 'common',
    icon: '🪃',
    description: 'Włócznia greckiego hoplity — główna broń falangi.',
    lore: 'Dory miało długość 2-3 metrów z grotem z kutego żelaza. Spartiaci ćwiczyli z włócznią od dziecka — agoge nie dawała wyboru. W falandze włócznia tworzyła ścianę stali nie do przebicia. Pod Termopilami 300 Spartiatów i ich sojusznicy przez 3 dni zatrzymywali milionową armię Kserksesa.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'thermopylae_shield_uncommon',
    battleId: 'thermopylae-480bc',
    name: 'Aspis — Tarcza Spartańska',
    category: 'armor',
    rarity: 'uncommon',
    icon: '🛡',
    description: 'Okrągła tarcza hoplity — kluczowy element falangi.',
    lore: 'Aspis z Lakonii (stąd "lakoniczny" styl mowy Spartan) ważył 8 kg. Spartańskie matki mówiły synom: "Z tarczą lub na tarczy" — wróć zwycięski lub poległy. Utrata tarczy w walce była hańbą większą niż śmierć. Tarcze w falandze chroniły nie tylko właściciela, ale też sąsiada z lewej strony.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'thermopylae_xiphon_uncommon',
    battleId: 'thermopylae-480bc',
    name: 'Kopis — Miecz Perski',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '⚔',
    description: 'Zagięty miecz wojownika perskiego.',
    lore: 'Persowie używali kopisa — krótkiego, zakrzywionego miecza do cięcia. W walce z hoplitami przez wąskie przejście w Termopilach ich przewaga liczebna była bezużyteczna. Tylko kilku żołnierzy mogło walczyć jednocześnie w Gorącym Przejściu. Trzy dni tej klęski dały reszcie Grecji czas na przygotowanie do obrony.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'thermopylae_helmet_rare',
    battleId: 'thermopylae-480bc',
    name: 'Korynt — Hełm Koryncki',
    category: 'armor',
    rarity: 'rare',
    icon: '⛑',
    description: 'Charakterystyczny hełm zakrywający całą twarz.',
    lore: 'Hełm koryncki chronił doskonale, ale ograniczał słuch i widoczność peryferyjną. Żołnierz w hełmie mógł widzieć tylko to, co przed sobą — idealne do walki w ciasnym wąwozie. Hełm Leonidasa, jeśli istniał, prawdopodobnie zdobili Persowie jako trofeum wojenne po zdradzie Efialtesa.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'thermopylae_inscription_rare',
    battleId: 'thermopylae-480bc',
    name: 'Epitaf Symonidesa',
    category: 'document',
    rarity: 'rare',
    icon: '📜',
    description: 'Słynny epitaf ku czci 300 Spartan.',
    lore: '"Wędrowcze, idź powiedz Sparcie, żeśmy tu polegli, jej prawom posłuszni" — Symonides z Keos napisał te słowa dla 300 poległych. Przez 2500 lat ten epigram jest symbolem poświęcenia. Stela z napisem do dziś stoi w Termopilach, gdzie 480 r. p.n.e. zatrzymano imperialny marsz Persji.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'thermopylae_leonidas_sword',
    battleId: 'thermopylae-480bc',
    name: 'Miecz Leonidasa',
    category: 'weapon',
    rarity: 'legendary',
    icon: '🗡',
    description: 'Legendarny miecz króla Sparty — symbol ostatecznego poświęcenia.',
    lore: 'Leonidas I wiedział, że idzie na śmierć. Wyrocznia delficka przepowiedziała: albo Sparta zginie, albo zginie jej król. Wybrał poświęcenie — ale nie daremne. 300 Spartan i 700 Tespiańczyków zginęło do ostatniego, dając Grecji czas na zorganizowanie oporu. Symboliczna broń Leonidasa stała się symbolem wolności.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Termopil',
    unlockedBy: 'complete',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Agincourt 1415 ──────────────────────────────
const AGINCOURT_ARTIFACTS: Artifact[] = [
  {
    id: 'agincourt_arrow_common',
    battleId: 'agincourt-1415',
    name: 'Strzała Łucznika',
    category: 'weapon',
    rarity: 'common',
    icon: '🏹',
    description: 'Angielska strzała z grochotem — grot przenikający zbroję.',
    lore: 'Pod Agincourt 6 000 angielskich łuczników wystrzeliło do 72 000 strzał na minutę w szarżującą francuską arystokrację. Angielski łuk długi (longbow) wymagał 10 lat ćwiczeń i deformował kręgosłup strzelca — kości łuczników z XV w. są asymetryczne. Strzały przenikały zbroję z odległości 50 metrów.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'agincourt_longbow_uncommon',
    battleId: 'agincourt-1415',
    name: 'Łuk Długi Walijski',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '🪃',
    description: 'Walijski łuk cisowy — broń która zmieniła średniowieczną wojnę.',
    lore: 'Walijski longbow wymagał siły naciągu 60-80 kg. Angielska piechota chłopskiego pochodzenia, po tygodniach ćwiczeń, mogła wysłać 10-12 strzał na minutę na odległość 300 metrów. To broń, która obaliła dominację rycerstwa i zdemokratyzowała wojnę — chłop mógł zabić króla.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'agincourt_plate_uncommon',
    battleId: 'agincourt-1415',
    name: 'Nagolennik Rycerski',
    category: 'armor',
    rarity: 'uncommon',
    icon: '⚙',
    description: 'Element pełnej zbroi płytowej z XV wieku.',
    lore: 'Pełna zbroja płytowa pod Agincourt ważyła 20-25 kg. Mokra, rozmarznięta gleba normandzka wciągała rycerzy pod stopami. Ciężko zbrojni, wyczerpani wycofywaniem się, nie mogli wstać samodzielnie po upadku. Angielczycy dobijali poległych krótkimi nożami przez szpary w wizjerze.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'agincourt_crown_rare',
    battleId: 'agincourt-1415',
    name: 'Korona Francji — replika',
    category: 'personal',
    rarity: 'rare',
    icon: '👑',
    description: 'Symbol roszczenia Henryka V do tronu Francji.',
    lore: 'Henryk V twierdził, że jest prawowitym królem Francji przez matkę. Bitwa pod Agincourt otworzyła mu drogę do Paryża i traktatu w Troyes (1420), w którym Karol VI uznał Henryka za dziedzica tronu Francji. Gdyby Henryk V nie umarł w 1422 roku, historia Europy mogłaby wyglądać zupełnie inaczej.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'agincourt_visor_rare',
    battleId: 'agincourt-1415',
    name: 'Wizjer Hełmu Przyłbicowego',
    category: 'armor',
    rarity: 'rare',
    icon: '⛑',
    description: 'Przyłbica hełmu francuskiego rycerza.',
    lore: 'Angielscy łucznicy celowo strzelali pod przyłbice i w szpary zbroi z bliskiej odległości. Kiedy Francuzi dotarli do angielskich pozycji po marszu przez błoto, byli tak wyczerpani, że ledwo trzymali broń. Henry V nakazał zabijać jeńców — bezprecedensowe działanie — gdy groziło odwrócenie bitwy.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'agincourt_henry_sword',
    battleId: 'agincourt-1415',
    name: 'Miecz Henryka V',
    category: 'weapon',
    rarity: 'legendary',
    icon: '🗡',
    description: 'Legendarny miecz zwycięskiego króla Anglii.',
    lore: '"Raz jeszcze w wyłom, drodzy przyjaciele, raz jeszcze!" — choć te słowa to Szekspir, Henryk V walczył osobiście pod Agincourt. Sam przyłączył się do obrony gdy zagrozili jeńcy. Miecz króla-wojownika stał się symbolem angielskiej tożsamości narodowej i jest przywoływany do dziś.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Agincourt',
    unlockedBy: 'complete',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Borodino 1812 ───────────────────────────────
const BORODINO_ARTIFACTS: Artifact[] = [
  {
    id: 'borodino_canteen_common',
    battleId: 'borodino-1812',
    name: 'Manierka Żołnierska',
    category: 'personal',
    rarity: 'common',
    icon: '🫙',
    description: 'Blaszana manierka żołnierza z kampanii 1812 roku.',
    lore: 'Kampania rosyjska Napoleona była katastrofą logistyczną. Armia wyruszyła z 400 000 żołnierzy — do Moskwy dotarło 100 000 zdolnych do walki. Upał, pragnienie, dyzenteria, epidemie zabiły więcej ludzi niż bitwy. Manierka była cenniejsza od broni, a często pełna zepsutej wody, która i tak zabijała.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'borodino_shako_uncommon',
    battleId: 'borodino-1812',
    name: 'Czako Piechoty Liniowej',
    category: 'armor',
    rarity: 'uncommon',
    icon: '🎩',
    description: 'Wysoka czapka francuskiej piechoty liniowej.',
    lore: 'Pod Borodino 7 września 1812 roku zginęło 70 000 żołnierzy w ciągu jednego dnia — najkrwawsza bitwa epoki. Napoleon poniósł 30 000 strat, Kutuzow — 40 000. Zwycięstwo Francuzów było pyrrusowe: zdobyli pole walki, ale nie rozbili armii rosyjskiej. Kutuzow wycofał się w porządku.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'borodino_cavalry_saber_uncommon',
    battleId: 'borodino-1812',
    name: 'Szabla Kawaleryjska',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '⚔',
    description: 'Szabla lekkiej kawalerii — ulans lub huzarzy.',
    lore: 'Pod Borodino kawaleria obu stron szarżowała wielokrotnie na bagnety i kartacze. Polscy ulanzy Napoleona znani byli z odwagi graniczącej z szaleństwem. Ney, Murat, Davout — marszałkowie walczyli osobiście. Napoleon po raz pierwszy nie wysłał Gwardii — ta ostrożność kosztowała go zwycięstwo.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'borodino_order_rare',
    battleId: 'borodino-1812',
    name: 'Order Świętego Jerzego',
    category: 'personal',
    rarity: 'rare',
    icon: '🎖',
    description: 'Rosyjski order wojskowy za waleczność pod Borodino.',
    lore: 'Order Świętego Jerzego był najwyższym rosyjskim odznaczeniem wojskowym — odpowiednikiem Légion d\'honneur. Pod Borodino generał Bagration, jeden z najlepszych rosyjskich dowódców, otrzymał śmiertelną ranę od odłamka. Jego śmierć i obrona umocnień Flèches stała się symbolem rosyjskiego heroizmu.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'borodino_icon_rare',
    battleId: 'borodino-1812',
    name: 'Ikona Pola Walki',
    category: 'personal',
    rarity: 'rare',
    icon: '🙏',
    description: 'Przenośna ikona noszona przez rosyjskich żołnierzy.',
    lore: 'Kutuzow przed bitwą przeżegnał wojsko ikoną Matki Bożej Smoleńskiej — ewakuowaną z oblężonego Smoleńska. Żołnierze rosyjscy walczyli z wiarą, że bronią Świętej Rusi. Ta wiara, połączona z rozkazem "nie cofać się", sprawiła, że pod Borodino Rosjanie ginęli na pozycjach zamiast się wycofywać.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'borodino_napoleon_hat',
    battleId: 'borodino-1812',
    name: 'Kapelusz Napoleona',
    category: 'personal',
    rarity: 'legendary',
    icon: '🎩',
    description: 'Symbol największego dowódcy epoki — w dniu jego klęski.',
    lore: 'Napoleona pod Borodino dopadła choroba — przeziębienie i częściowe zapalenie gruczołu krokowego. Był powolny w decyzjach, nie wysłał Gwardii, nie wykorzystał sukcesu. Nikt nie odważył się mu powiedzieć, że przegrywa. Jego kapelusz dwurożny (bicorne) stał się jednym z najbardziej rozpoznawalnych symboli historycznych.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Borodino',
    unlockedBy: 'complete',
    xpReward: 400, coinReward: 150,
  },
];

// ── Artefakty Gettysburg 1863 ─────────────────────────────
const GETTYSBURG_ARTIFACTS: Artifact[] = [
  {
    id: 'gettysburg_bullet_common',
    battleId: 'gettysburg-1863',
    name: 'Kula Minié',
    category: 'weapon',
    rarity: 'common',
    icon: '⚫',
    description: 'Stożkowa kula karabinowa — rewolucja w śmiercionośności.',
    lore: 'Kula Minié, wynaleziona w 1849 roku, uczyniła wojnę domową najkrwawszą w historii Ameryki. Gwintowane lufy z kulą Minié były 5 razy celniejsze od muszkietu, ale taktykę piechoty zupełnie ignorowały. Dowódcy wciąż atakowali w zwartych szeregach — i ginęli tysiącami. Pod Gettysburgiem 51 000 ofiar w 3 dni.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'gettysburg_kepi_uncommon',
    battleId: 'gettysburg-1863',
    name: 'Kepi Unii',
    category: 'armor',
    rarity: 'uncommon',
    icon: '🪖',
    description: 'Niebieska czapka żołnierza Unii.',
    lore: 'Niebieski mundur Unii i szary Konfederacji — proste rozróżnienie, które w dymie prochowym i zamęcie bitwy bywało niewystarczające. Pod Gettysburgiem oddziały strzelały do własnych. Kolor stał się symbolem podziału, który trwa w kulturze amerykańskiej do dziś. Na cmentarzu gettysburskim spoczywa 3 500 żołnierzy Unii.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'gettysburg_gray_cap_uncommon',
    battleId: 'gettysburg-1863',
    name: 'Szara Czapka Konfederacji',
    category: 'armor',
    rarity: 'uncommon',
    icon: '🧢',
    description: 'Szara czapka żołnierza Skonfederowanych Stanów.',
    lore: 'Lee wkraczając do Pensylwanii, wierzył że zwycięstwo pod Gettysburgiem zmusi Unię do pokoju. Jego żołnierze — weterani Antietam i Chancellorsville — byli pewni zwycięstwa. Szarża Picketta 3 lipca była ostatnią szansą Południa. 15 000 ludzi weszło w otwarte pole pod ogień unijnej artylerii. Wróciło 5 000.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'gettysburg_speech_rare',
    battleId: 'gettysburg-1863',
    name: 'Adres Gettysburski',
    category: 'document',
    rarity: 'rare',
    icon: '📜',
    description: 'Jedno z najważniejszych przemówień w historii Ameryki.',
    lore: 'Lincoln wygłosił Adres Gettysburski 19 listopada 1863 roku na otwarciu cmentarza wojskowego. "Rząd ludu, przez lud, dla ludu nie zginie z powierzchni ziemi" — 272 słowa, które zredefiniowały cel wojny. Lincoln myślał, że przemówienie nie wypadło dobrze. Historia okazała się innego zdania.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'gettysburg_cannon_rare',
    battleId: 'gettysburg-1863',
    name: 'Łuska Artyleryjska',
    category: 'weapon',
    rarity: 'rare',
    icon: '💣',
    description: 'Łuska z armat unijnych na Cemetery Hill.',
    lore: 'Unia rozmieściła 372 działa wzdłuż "Rybiej Ości" — wzgórz tworzących defensywną linię. Konfederaci otworzyli ogień z 170 dział — największy ostrzał artyleryjski w historii Ameryki Północnej. Dym prochowy był tak gęsty, że żołnierze nie widzieli własnych rąk. Huk słyszano w odległości 240 km.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'gettysburg_lee_sword',
    battleId: 'gettysburg-1863',
    name: 'Miecz Roberta E. Lee',
    category: 'weapon',
    rarity: 'legendary',
    icon: '🗡',
    description: 'Symbol największego generała Południa — w jego gorzkim dniu.',
    lore: 'Po klęsce pod Gettysburgiem Lee napisał do Davisa: "To wszystko moja wina". Wziął odpowiedzialność za szarżę Picketta i inne decyzje. Przez dwa lata walczył dalej, wiedząc że przegra. Appomattox, 9 kwietnia 1865: Lee oddał miecz Grantowi. Ten zwrócił mu go z szacunkiem. Gest który zakończył wojnę braterską.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Gettysburga',
    unlockedBy: 'complete',
    xpReward: 400, coinReward: 150,
  },
];

// ── Artefakty Bitwa o Anglię 1940 ─────────────────────────
const BRITAIN_ARTIFACTS: Artifact[] = [
  {
    id: 'britain_wings_common',
    battleId: 'britain-1940',
    name: 'Odznaka Pilota RAF',
    category: 'personal',
    rarity: 'common',
    icon: '🪽',
    description: 'Srebrne skrzydła pilota RAF — symbol Bitwy o Anglię.',
    lore: '"Nigdy w dziejach ludzkich konfliktów tak wielu nie zawdzięczało tak wiele tak nielicznym" — Churchill o pilotach RAF. Średni wiek pilota w 1940 roku: 20 lat. Przeżywalność pilota po trafieniu: znikoma. Mimo to do RAF zgłaszali się ochotnicy z całej wolnej Europy — Polacy, Czesi, Francuzi, Kanadyjczycy.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'britain_spitfire_part_uncommon',
    battleId: 'britain-1940',
    name: 'Część Spitfire\'a Mk I',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '✈',
    description: 'Metalowy element elipsowalnego skrzydła legendarnego myśliwca.',
    lore: 'Spitfire Mk I osiągał 582 km/h i mógł pokonać Bf 109E w walce kołowej. Jego elliptyczne skrzydła — droższe w produkcji — dawały doskonałą zwrotność. Mitchell, jego projektant, zmarł na raka zanim zobaczył jak Spitfire ratuje Anglię. Fabryki pracowały 24 godziny na dobę, kobiety budowały samoloty ramię w ramię z mężczyznami.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'britain_radar_map_uncommon',
    battleId: 'britain-1940',
    name: 'Mapa Sieci Radarowej',
    category: 'document',
    rarity: 'uncommon',
    icon: '📡',
    description: 'Schemat Chain Home — systemu radarowego który wygrał bitwę.',
    lore: 'Sieć radarów Chain Home ostrzegała przed atakami z odległości 200 km — rewolucja w obronie powietrznej. Niemcy mieli radary, ale nie rozumieli jak je systemowo wykorzystać. RAF zawdzięczał przetrwanie nie liczbie samolotów, ale inteligencji operacyjnej: radarowi, łączności i systemowi dystrybucji sił.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'britain_bf109_plate_rare',
    battleId: 'britain-1940',
    name: 'Tabliczka Bf 109E',
    category: 'weapon',
    rarity: 'rare',
    icon: '⚙',
    description: 'Fragment nieprzyjaciela zestrzelonego nad Anglią.',
    lore: 'Bf 109E był równy Spitfire\'owi, ale miał jeden fatalny minus: zasięg zaledwie 10 minut nad Londynem. Piloci Luftwaffe bali się kanału bardziej niż Spitfire\'ów — zestrzelony nad Anglią oznaczał jeńca. Niemcy stracili 1887 samolotów, RAF — 1023. Statystyki nie oddają jednak faktu, że piloci RAF wrócili do walki.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'britain_churchill_speech_rare',
    battleId: 'britain-1940',
    name: 'Stenogram Mowy Churchilla',
    category: 'document',
    rarity: 'rare',
    icon: '📜',
    description: '"Będziemy walczyć na plażach" — słowa które ocaliły morale.',
    lore: 'Churchill w sierpniu 1940 roku był praktycznie sam. Francja skapitulowała, Ameryka neutralna, Związek Radziecki w sojuszu z Hitlerem. "Nigdy nie skapitulujemy" — powiedział przed parlamentem. Jego retoryka utrzymywała wolę walki gdy wszystkie kalkulacje wskazywały na klęskę. Słowa bywają bronią.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'britain_raf_ace_medal',
    battleId: 'britain-1940',
    name: 'Medal Wybitnych Lotników DFC',
    category: 'personal',
    rarity: 'legendary',
    icon: '🏅',
    description: 'Distinguished Flying Cross — najwyższe odznaczenie pilotów RAF.',
    lore: 'Douglas Bader — pilot bez nóg (amputowanych po wypadku w 1931!) — latał Spitfire\'em i zestrzelił 20 samolotów. Marmaduke Pattle — 51 zwycięstw, najmniej znany as wśród wielkich. Polscy piloci z 303 Dywizjonu zestrzelili więcej samolotów niż jakikolwiek inny dywizjon RAF. DFC przyznano im pośmiertnie, bo Anglia oddała Polskę Stalinowi.',
    unlockCondition: 'Odwiedź Biggin Hill (GPS)',
    unlockedBy: 'visit_gps',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Stalingrad 1942-43 ──────────────────────────
const STALINGRAD_ARTIFACTS: Artifact[] = [
  {
    id: 'stalingrad_ppsh_common',
    battleId: 'stalingrad-1942',
    name: 'PPSz-41 — Pistolet Maszynowy',
    category: 'weapon',
    rarity: 'common',
    icon: '🔫',
    description: 'Radziecki pistolet maszynowy — idealna broń do walki miejskiej.',
    lore: 'W ruinach Stalingradu walczono piwnica po piwnicy, pokój po pokoju. PPSz-41 z 71-nabojowym bębnem był idealny do tej walki. Niemcy przezywali go "Hitlersäge" — piła Hitlera — od charakterystycznego dźwięku przy strzale. Prosta, tania, niezawodna broń produkowana przez miliony. Wygrała bitwę uliczną.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'stalingrad_sniper_card_uncommon',
    battleId: 'stalingrad-1942',
    name: 'Karta Snajpera',
    category: 'personal',
    rarity: 'uncommon',
    icon: '🎯',
    description: 'Radziecki certyfikat snajpera z kwalifikowanymi celami.',
    lore: 'Wasilij Zajcew z 225 potwierdzonymi trafieniami stał się symbolem obrony Stalingradu. Snajperzy strzelali przez okna, przez otwory w ścianach, z ruin. Niemcy wysłali Major Königa — asa snajperskiego — żeby go wyeliminować. Pojedynek trwał kilka dni. Zajcew żył. König nie. Bitwa snajperów to symbol Stalingradu.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'stalingrad_field_ration_uncommon',
    battleId: 'stalingrad-1942',
    name: 'Racje Żywnościowe Zimy',
    category: 'personal',
    rarity: 'uncommon',
    icon: '🧊',
    description: 'Symbol głodu i mrozu oblężonych Niemców.',
    lore: 'Po okrążeniu przez Operację Uran (listopad 1942) 6. Armia Paulusa miała racje na 10 dni. Göring obiecał dostawy powietrzne — 300 ton dziennie. Dostała 100 ton, w najlepsze dni. Żołnierze jedli konie, szczury, skórę z butów. Temperatura -30°C. Z 300 000 okrążonych przeżyło 91 000. Do Niemiec wróciło 6 000.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'stalingrad_paulus_order_rare',
    battleId: 'stalingrad-1942',
    name: 'Rozkaz Kapitulacji Paulusa',
    category: 'document',
    rarity: 'rare',
    icon: '📋',
    description: 'Historyczny dokument — kapitulacja 6. Armii.',
    lore: '2 lutego 1943: feldmarszałek Paulus, mianowany 30 stycznia (by nie dał się wziąć do niewoli — marszałkowie nie kapitulują), złożył broń. Był pierwszym niemieckim feldmarszałkiem, który trafił do sowieckiej niewoli. Hitler wpadł w szał. Stalingrad był punktem zwrotnym — od tej chwili Niemcy tylko się cofali.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'stalingrad_dom_pavlova_rare',
    battleId: 'stalingrad-1942',
    name: 'Cegła z Domu Pawłowa',
    category: 'personal',
    rarity: 'rare',
    icon: '🧱',
    description: 'Fragment budynku bronionego przez 58 dni.',
    lore: 'Dom Pawłowa — cztero-piętrowy apartamentowiec przy Placu 9 Stycznia — był broniony przez sierżanta Jakowa Pawłowa i 24 żołnierzy przez 58 dni. Mały garnizon odparł setki ataków. Żukow podobno powiedział, że Niemcy stracili pod tym jednym domem więcej żołnierzy niż przy zdobywaniu Paryża w 1940 roku.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'stalingrad_mamayev_kurgan',
    battleId: 'stalingrad-1942',
    name: 'Ziemia z Mamajewa Kurganu',
    category: 'personal',
    rarity: 'legendary',
    icon: '⛰',
    description: 'Symbol największej bitwy w historii — 140 dni o jeden wzgórz.',
    lore: 'Mamajew Kurgan zmienił właściciela 13 razy w ciągu jednej doby walk. Żołnierze walczyli o każdy metr wzgórza — bo kontrolował pole widoku całego Stalingradu. Po wojnie ziemia kurganu była tak przesiąknięta metalem, że przez lata nie rosła na nim trawa. Dziś stoi tam "Ojczyzna wzywa" — 87-metrowa statua. Odwiedź ją.',
    unlockCondition: 'Odwiedź Mamajew Kurgan (GPS)',
    unlockedBy: 'visit_gps',
    xpReward: 400, coinReward: 150,
  },
];

// ── Artefakty Maraton 490 p.n.e. ──────────────────────────
const MARATHON_ARTIFACTS: Artifact[] = [
  {
    id: 'marathon_sandal_common',
    battleId: 'marathon-490bc',
    name: 'Sandał Grecki',
    category: 'personal',
    rarity: 'common',
    icon: '👡',
    description: 'Sandał hoplity z 490 roku p.n.e.',
    lore: 'Fejdyppides przebiegł 40 km z Maratonu do Aten by ogłosić zwycięstwo — i padł martwy. Tak głosi legenda, która dała nazwę maratonowi. W rzeczywistości Fejdyppides prawdopodobnie przebiegł wcześniej 240 km z Aten do Sparty po pomoc — i odmowę. Grecy wygrali sami, bez Sparty.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'marathon_bronze_tip_uncommon',
    battleId: 'marathon-490bc',
    name: 'Brązowy Grot Włóczni',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '🪃',
    description: 'Grot dory z brązu z V wieku p.n.e.',
    lore: 'Miltiades rozkazał Grekom biec w stronę Persów — niesłychane, bo falanga ruszała krokiem. Bieg zakłócał szyki perskich łuczników, skrócił czas wystawienia na strzały. 10 000 Ateńczyków i Platejczyków zaatakowało 25 000 Persów. Falanga po skrzydłach wzięła Persów w kleszcze. Straty: 192 Greków, 6 400 Persów.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'marathon_persian_bow_uncommon',
    battleId: 'marathon-490bc',
    name: 'Łuk Perski',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '🏹',
    description: 'Refleksyjny łuk perskiego łucznika.',
    lore: 'Persowie polegali na łucznikach — najlepszych w świecie starożytnym. Ich refleksyjne łuki kompozytowe miały zasięg 300 metrów. Pod Maratonem to nie pomogło: Ateńczycy zbliżyli się biegiem, falanga zwarła szyki zanim łucznicy zdążyli strzelić. Kontakt ręka w rękę eliminował przewagę dystansową.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'marathon_trophy_rare',
    battleId: 'marathon-490bc',
    name: 'Tropaion — Trofeum Bitewne',
    category: 'personal',
    rarity: 'rare',
    icon: '🏆',
    description: 'Replika pomnika wzniesionego na polu bitwy przez Aten.',
    lore: 'Grecy zwyczajowo wznosili tropaion — drzewo z zawieszoną zbroją wroga — w miejscu gdzie nieprzyjaciel się odwrócił do ucieczki. Maraton był punktem zwrotnym w historii Europy: pierwsze zwycięstwo Hellady nad imperium. Ateny stały się hegemonem Grecji. Flota zbudowana z tego prestiżu wygrała Salaminę 10 lat później.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'marathon_miltiades_helmet_rare',
    battleId: 'marathon-490bc',
    name: 'Hełm Miltiadesa',
    category: 'armor',
    rarity: 'rare',
    icon: '⛑',
    description: 'Hełm stratega który wygrał Maraton.',
    lore: 'Miltiades podarował swój hełm do sanktuarium w Olimpii — archeolodzy odkopali go w 1961 roku. Napis: "Miltiades poświęca bogom". Wróg publiczny numer jeden Persji ofiarował hełm po zwycięstwie. Niedługo potem Ateńczycy skazali go na więzienie za nieudaną wyprawę na Paros. Tak Ateny nagradzały bohaterów.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'marathon_soros_stone',
    battleId: 'marathon-490bc',
    name: 'Kamień z Soros',
    category: 'personal',
    rarity: 'legendary',
    icon: '⛰',
    description: 'Fragment kurhanu 192 poległych Ateńczyków.',
    lore: 'Soros — kopiec ziemi na polu bitwy — kryje szczątki 192 Ateńczyków poległych pod Maratonem. Pochówek na polu bitwy był wyjątkowy: zazwyczaj ciała wracały do polis. Ten zaszczyt był uznaniem za heroizm. Do dziś w Maratonie odbywają się biegi upamiętniające bitwę. 2500 lat po starożytności, ludzie wciąż biegną tą samą drogą.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Maratonu',
    unlockedBy: 'complete',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Lepanto 1571 ────────────────────────────────
const LEPANTO_ARTIFACTS: Artifact[] = [
  {
    id: 'lepanto_crucifix_common',
    battleId: 'lepanto-1571',
    name: 'Krzyż Marynarza',
    category: 'personal',
    rarity: 'common',
    icon: '✝',
    description: 'Mały krzyż noszony przez marynarzy Ligi Świętej.',
    lore: 'Papież Pius V ogłosił Lepanto bitwą krucjatową i nakazał modlitwy różańcowe po całym chrześcijaństwie. Marynarz płynący w tę bitwę wiedział, że walczy "za Chrystusa". Osmanie walczyli "za Allacha i Sułtana". Lepanto było ostatnią wielką bitwą między flotami wiosłowymi — i ostatnią bitwą religijną na morzu.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'lepanto_oar_uncommon',
    battleId: 'lepanto-1571',
    name: 'Wiosło Galery',
    category: 'personal',
    rarity: 'uncommon',
    icon: '🚣',
    description: 'Wiosło galernika — więźnia lub skazańca na galei.',
    lore: 'Miguel de Cervantes — przyszły autor Don Kichota — walczył pod Lepanto i stracił lewą rękę. Trafił do niewoli osmańskiej na 5 lat. Wierszem opisał bitwę jako "najwspanialszą okazję jaką wieki minione i przyszłe widziały". Skazańcy przykuci do wioseł nie mieli wyjścia: albo walczyli, albo tonęli.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'lepanto_cannon_ball_uncommon',
    battleId: 'lepanto-1571',
    name: 'Kula Armatnia',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '⚫',
    description: 'Żeliwna kula okrętowa z bitwy pod Lepanto.',
    lore: 'Liga Święta miała technologiczną przewagę: galery wyposażone w ciężkie działa. Osmanie polegali na łucznikach i abordażu — tradycyjnej taktyce morskiej. Gdy chrześcijanie otworzyli ogień z bliskiej odległości, osmańskie galery płonęły zanim zdążyły się zbliżyć. Lepanto zademonstrowano militarną przewagę Zachodu.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'lepanto_ali_pasha_banner_rare',
    battleId: 'lepanto-1571',
    name: 'Fragment Sztandaru Ali Paszy',
    category: 'personal',
    rarity: 'rare',
    icon: '🚩',
    description: 'Osmański sztandar dowódcy floty — zdobyty jako trofeum.',
    lore: 'Ali Pasza dowodził flotą osmańską z galery-admiralicji Sultana. Gdy zginął w starciu i jego głowa została wzniesiona na piku, morale osmańskie załamało się. Don Juan de Austria, dowódca Ligi, nakazał zawiązać osmańskie chorągwie na tyłach swoich galer — symbol triumfu. Wzięto 15 000 jeńców, uwolniono 15 000 chrześcijańskich galernisków.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'lepanto_rosary_rare',
    battleId: 'lepanto-1571',
    name: 'Różaniec Papieża Piusa V',
    category: 'personal',
    rarity: 'rare',
    icon: '📿',
    description: 'Symbol bitwy jako odpowiedzi na modlitwy.',
    lore: 'Pius V modlił się przez całą bitwę w Watykanie. Według relacji, miał wizję zwycięstwa w tej samej chwili gdy Liga zwyciężyła pod Lepanto — wiele godzin zanim dotarły oficjalne wieści. Ustanowił święto Matki Boskiej Różańcowej (7 października) na pamiątkę bitwy. Do dziś obchodzone w Kościele katolickim.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'lepanto_don_juan_armor',
    battleId: 'lepanto-1571',
    name: 'Napierśnik Don Juana de Austria',
    category: 'armor',
    rarity: 'legendary',
    icon: '🛡',
    description: 'Zbroja dowódcy, który poprowadził Ligę do zwycięstwa.',
    lore: 'Don Juan de Austria — nieślubny syn Karola V, przyrodni brat Filipa II — miał 24 lata gdy dowodził flotą 212 okrętów pod Lepanto. Wyjechał na dziób swojej galery wśród ostrzału — demonstrując odwagę, która dodawała ducha żołnierzom. Zwycięstwo pod Lepanto zatrzymało osmańską ekspansję na zachodzie Morza Śródziemnego.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Lepanto',
    unlockedBy: 'complete',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Austerlitz 1805 ─────────────────────────────
const AUSTERLITZ_ARTIFACTS: Artifact[] = [
  {
    id: 'austerlitz_epaulette_common',
    battleId: 'austerlitz-1805',
    name: 'Naramiennik Oficerski',
    category: 'armor',
    rarity: 'common',
    icon: '⭐',
    description: 'Złoty naramiennik oficera Wielkiej Armii Napoleona.',
    lore: 'Austerlitz nazywają "Bitwą Trzech Cesarzy": Napoleon, Aleksander I i Franciszek II stanęli naprzeciwko siebie. Napoleon w ciągu jednego dnia pokonał armię dwóch cesarstw i praktycznie zakończył istnienie Świętego Cesarstwa Rzymskiego — największy triumf dyplomatyczny i militarny w jego karierze.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'austerlitz_drum_uncommon',
    battleId: 'austerlitz-1805',
    name: 'Bęben Marszowy',
    category: 'personal',
    rarity: 'uncommon',
    icon: '🥁',
    description: 'Bęben taktyczny Wielkiej Armii — rytm bitwy.',
    lore: 'W epoce napoleońskiej rozkazy wydawano przez bębny i trąbki — inaczej żołnierze w huku bitwy nie słyszeli dowódców. Taktycy ćwiczyli rozróżnianie 30 różnych rytmów. Pod Austerlitz Napoleon zaplanował całą bitwę w noc poprzedzającą — każde uderzenie bębna było elementem scenariusza. Zadziałał perfekcyjnie.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'austerlitz_frozen_lake_ice_uncommon',
    battleId: 'austerlitz-1805',
    name: 'Odłamek Lodu z Satschańskiego Jeziora',
    category: 'personal',
    rarity: 'uncommon',
    icon: '🧊',
    description: 'Symbol końca bitwy — artyleria rozbiła lód pod uciekającymi.',
    lore: 'Po rozbiciu armii sprzymierzonej, tysiące żołnierzy uciekało przez zamarznięte jeziora Satschan i Mönitz. Napoleon nakazał otworzyć ogień artyleryjski — lód pękł, 2 000 ludzi utonęło. Żołnierze zamarzali w wodzie, niektórzy ze szwadronów kawalerii razem z końmi. Piękny i okrutny koniec najpiękniejszej bitwy Napoleona.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'austerlitz_sun_of_austerlitz_rare',
    battleId: 'austerlitz-1805',
    name: 'Słońce Austerlitz',
    category: 'personal',
    rarity: 'rare',
    icon: '☀',
    description: 'Złoty medal z motywem wschodzącego słońca — symbol bitwy.',
    lore: '"Słońce Austerlitz" — Napoleon przed każdą bitwą wspominał wschodnie słońce tego poranka. Mgła ukrywała manewry, a gdy słońce wzeszło, odsłoniło słabość pozycji sprzymierzonych na Pratzen Heights. Napoleon czekał na ten moment z zimną krwią przez 3 godziny. Moment ataku był jak zegarmistrz.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'austerlitz_treaty_rare',
    battleId: 'austerlitz-1805',
    name: 'Traktat Bratysławski',
    category: 'document',
    rarity: 'rare',
    icon: '📜',
    description: 'Traktat pokojowy wymuszony po Austerlitz.',
    lore: 'Traktat z Presburga (Bratysławy) 26 grudnia 1805 — podpisany przez pokonanego Franciszka II — rozwiązał praktycznie Świętą Rzeszę Narodu Niemieckiego. Austria straciła Tyrol, Wenecję, Istrię. Napoleon stał się hegemonem Europy. Ale ta hegemonia trwała tylko 9 lat — Rosja i Prusada nie zapomniały upokorzenia.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'austerlitz_imperial_eagle',
    battleId: 'austerlitz-1805',
    name: 'Orzeł Cesarski Austerlitz',
    category: 'personal',
    rarity: 'legendary',
    icon: '🦅',
    description: 'Złoty orzeł Napoleona — zdobyty przez stulecia pamięci.',
    lore: 'Austerlitz było szczytem napoleońskiej potęgi. 73 000 Francuzów rozbiło 85 000 Austriaków i Rosjan w 9 godzin, przy stratach 9 000 do 36 000. Napoleon powiedział: "Żołnierze, jestem z was zadowolony!". Na łuku triumfalnym w Paryżu wyryto imiona 558 generałów i 95 bitew. Austerlitz jest pierwsza na liście. Jako ostatni symbol tej chwały.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Austerlitz',
    unlockedBy: 'complete',
    xpReward: 400, coinReward: 150,
  },
];

// ── Artefakty Somma 1916 ──────────────────────────────────
const SOMME_ARTIFACTS: Artifact[] = [
  {
    id: 'somme_whistle_common',
    battleId: 'somme-1916',
    name: 'Gwizdek Oficerski',
    category: 'personal',
    rarity: 'common',
    icon: '🎵',
    description: 'Mosiężny gwizdek — sygnał do ataku 1 lipca 1916.',
    lore: 'O 7:30 rano 1 lipca 1916 roku, na froncie długości 40 km, oficerowie gwizdnęli jednocześnie. Wyszło 120 000 żołnierzy. Niemcy wyszli z bunkrów i otworzyli ogień karabinów maszynowych. Do wieczoru padło 57 470 Brytyjczyków — z czego 19 240 zabitych. To był najczarniejszy dzień w historii brytyjskiej armii.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'somme_tank_part_uncommon',
    battleId: 'somme-1916',
    name: 'Część Czołgu Mark I',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '⚙',
    description: 'Fragment pierwszego czołgu użytego w historii.',
    lore: '15 września 1916 roku Brytyjczycy użyli 49 czołgów Mark I po raz pierwszy w historii. "Machiny piekielne" — pisały berlińskie gazety. Czołgi poruszały się z prędkością 6 km/h, psuły co chwilę, ale siały terror w okopach niemieckich. Haig użył ich za wcześnie i za mało — zmarnował element zaskoczenia.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'somme_letter_home_uncommon',
    battleId: 'somme-1916',
    name: 'List Nieotwarty',
    category: 'document',
    rarity: 'uncommon',
    icon: '✉',
    description: 'List wysłany przed atakiem — nigdy nieotwarty przez rodzinę.',
    lore: 'Przed wielką ofensywą żołnierze pisali listy "na wypadek". Rodziny dostawały je od wojska jeśli żołnierz poległ. Wiele rodzin nie otwierało takich kopert przez lata — nie mogąc pogodzić się ze stratą. Listy z Sommy, które przetrwały w archiwach, są dziś najpotężniejszym dokumentem o cenie I Wojny Światowej.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'somme_haig_order_rare',
    battleId: 'somme-1916',
    name: 'Rozkaz Dzienny Haiga',
    category: 'document',
    rarity: 'rare',
    icon: '📋',
    description: 'Kontrowersyjny rozkaz generała Haiga — "Rzeźnika z Sommy".',
    lore: 'Douglas Haig — "Butcher Haig", Rzeźnik z Sommy — był odpowiedzialny za plan ofensywy. Wierzył, że Niemcy uciekną po 7-dniowym bombardowaniu artyleryjskim. Niemcy siedzieli w 12-metrowych bunkrach — nienaruszeni. Haig nie zmienił taktyki. Somma kosztowała 420 000 brytyjskich ofiar, 200 000 francuskich i 500 000 niemieckich.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'somme_pals_badge_rare',
    battleId: 'somme-1916',
    name: 'Odznaka Pals Battalion',
    category: 'personal',
    rarity: 'rare',
    icon: '🎖',
    description: 'Odznaka batalionu przyjaciół — którzy razem polegli.',
    lore: '"Pals Battalions" — Brytyjczycy zachęcali przyjaciół, sąsiadów, kolegów z pracy do wstępowania razem. Calderdale Pals, Leeds Pals, Bradford Pals — w jeden dzień 1 lipca całe miasta traciły wszystkich mężczyzn jednocześnie. Sheffield stracił 513 z 600 żołnierzy w kilka minut. Cała generacja jednego miasteczka — znikała razem.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'somme_thiepval_memorial',
    battleId: 'somme-1916',
    name: 'Cegła Pomnika Thiepval',
    category: 'personal',
    rarity: 'legendary',
    icon: '🏛',
    description: 'Symbol 72 195 Brytyjczyków bez grobu.',
    lore: 'Pomnik w Thiepval nosi 72 195 imion żołnierzy Wspólnoty Brytyjskiej poległych nad Sommą, których ciał nie znaleziono. Pod Sommą ziemia wchłonęła tyle ludzkiego ciała, że szczątki odkrywa się do dziś — w ogródkach, przy robotach budowlanych. W 2016 roku, w setną rocznicę, Francuzi i Brytyjczycy stanęli razem w ciszy.',
    unlockCondition: 'Odwiedź Thiepval (GPS)',
    unlockedBy: 'visit_gps',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Kursk 1943 ──────────────────────────────────
const KURSK_ARTIFACTS: Artifact[] = [
  {
    id: 'kursk_shell_common',
    battleId: 'kursk-1943',
    name: 'Łuska Pancerna',
    category: 'weapon',
    rarity: 'common',
    icon: '💣',
    description: 'Łuska pocisku przeciwpancernego z bitwy pod Kurskiem.',
    lore: 'Pod Kurskiem starły się największe siły pancerne w historii: 6 000 czołgów po obu stronach. Niemcy postawili na Tygrysy i Pantery — nowocześniejsze, ale droższe i awariesnie. Sowieci mieli T-34 — prostsze, tańsze, produkowane masowo. Jeden Tygrys równał się 10 T-34 w walce, ale Sowieci mieli ich 20.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'kursk_landmine_uncommon',
    battleId: 'kursk-1943',
    name: 'Mina Przeciwczołgowa TM-41',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '💥',
    description: 'Sowiecka mina przeciwczołgowa — klucz do obrony Kurskiego łuku.',
    lore: 'Sowieci zaplanowali obronę elastyczną: pola minowe, okopy, linie obronne w głąb, rezerwy pancerne. Na metr kwadratowy łuku kurskiego przypadało 7 min i 1 500 metrów drutu kolczastego. Niemcy tracili czołgi na minach zanim dotarli do sowieckich pozycji. Zhukov i Rokossowski przygotowywali się 3 miesiące.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'kursk_tiger_vision_uncommon',
    battleId: 'kursk-1943',
    name: 'Celownik Czołgisty',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '🔭',
    description: 'Celownik optyczny z Tygrysa I lub Pantery.',
    lore: 'Bitwa pod Prochorowką (12 lipca 1943) — "największa bitwa pancerna w historii" — była chaosem. Czołgi walczyły z odległości kilku metrów, bo tylko tak T-34 mógł przebić pancerz Tygrysa. Sowieci stracili 700 czołgów, Niemcy 300, ale to Niemcy musieli się wycofać. Prochorowka była pirrusiowym zwycięstwem Sowietów.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'kursk_partisan_medal_rare',
    battleId: 'kursk-1943',
    name: 'Medal Partyzanta',
    category: 'personal',
    rarity: 'rare',
    icon: '🎖',
    description: 'Odznaczenie dla partyzantów aktywnych podczas operacji.',
    lore: 'Sowieccy partyzanci na tyłach niemieckich sabotowali linie kolejowe przez całą Operację Cytadela. "Operacja Szyna" — skoordynowana akcja sabotażu — uniemożliwiła Niemcom normalne dostawy amunicji. Partyzanci wysadzali mosty i tory w chwili gdy każdy wagon był na wagę złota. Frontowe sukcesy i walka na tyłach były ze sobą nierozerwalnie połączone.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'kursk_cipher_rare',
    battleId: 'kursk-1943',
    name: 'Rozszyfrowany Rozkaz Enigmy',
    category: 'document',
    rarity: 'rare',
    icon: '📋',
    description: 'Kopia depeszy z Ultra — rozkaz operacji Cytadela.',
    lore: 'Alianty i Sowieci znali plan "Cytadeli" miesiące przed jego realizacją — dzięki Ultra, złamaniu szyfru Enigmy. Stalin wiedział o dacie, kierunkach i siłach ataku. Mimo to pozwolił Niemcom zaatakować — żeby zniszczyć ich siły pancerne w przygotowanej obronie. Ta wiedza kosztowała więcej niż samo złamanie kodu.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'kursk_t34_hatch',
    battleId: 'kursk-1943',
    name: 'Właz T-34',
    category: 'weapon',
    rarity: 'legendary',
    icon: '⚙',
    description: 'Stalowy właz sowieckiego T-34 — czołgu który wygrał wojnę.',
    lore: 'T-34/76 pod Kurskiem był już przestarzały — Pantera była lepsza. Ale T-34 był produkowany przez 58 000 sztuk — każdy trafiony był zastępowany przez dwa nowe. Pod Kurskiem Niemcy wygrali technicznie, ale przegrali strategicznie: wyczerpali rezerwy pancerne bez przełomu. Po Kursku Niemcy nigdy już nie ofensywali na wschodzie. T-34 był tego symbolem.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Kurska',
    unlockedBy: 'complete',
    xpReward: 400, coinReward: 150,
  },
];

// ── Artefakty Cannae 216 p.n.e. ─────────────────────────
const CANNAE_ARTIFACTS: Artifact[] = [
  {
    id: 'cannae_gladius_common',
    battleId: 'cannae-216bc',
    name: 'Gladius Legionisty',
    category: 'weapon',
    rarity: 'common',
    icon: '⚔',
    description: 'Krótki miecz rzymskiego legionisty — broń, która zbudowała imperium.',
    lore: 'Gladius hispanicus — krótki miecz do pchnięć — był bronią idealną do walki w zwartym szyku. Pod Kannami 80 000 Rzymian walczyło tymi mieczami, ale zwarte szeregi stały się pułapką gdy Hannibal okrążył legiony. Gladius był bezużyteczny w tłoku — żołnierze nie mieli miejsca na zamach.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'cannae_falcata_uncommon',
    battleId: 'cannae-216bc',
    name: 'Falcata Iberyjska',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '🗡',
    description: 'Zakrzywiony miecz iberyjskiego najemnika Hannibala.',
    lore: 'Hannibal rekrutował najemników z całego Śródziemnomorza — Iberów, Galów, Numidów. Falcata, zakrzywiony miecz iberyjski, była tak skuteczna że Rzymianie próbowali ją kopiować. Pod Kannami to właśnie iberyjscy i galijscy piechurzy w centrum szyku cofali się celowo, wciągając legiony w pułapkę.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'cannae_scutum_uncommon',
    battleId: 'cannae-216bc',
    name: 'Scutum — Tarcza Legionowa',
    category: 'armor',
    rarity: 'uncommon',
    icon: '🛡',
    description: 'Wielka prostokątna tarcza legionisty — symbol Rzymu.',
    lore: 'Scutum ważył 10 kg i chronił ciało od ramienia do kolana. W formacji testudo (żółw) tarcze tworzyły nieprzeniknioną ścianę. Pod Kannami formacja ta była bezużyteczna — okrążeni legioniści byli ściskani tak ciasno, że nie mogli podnieść tarczy. To był geniusz Hannibala: obrócić siłę Rzymu przeciw niemu.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'cannae_ring_rare',
    battleId: 'cannae-216bc',
    name: 'Pierścienie Senatorskie',
    category: 'personal',
    rarity: 'rare',
    icon: '💍',
    description: 'Złote pierścienie zebrane z ciał poległych senatorów rzymskich.',
    lore: 'Po bitwie Hannibal nakazał zebrać złote pierścienie z ciał poległych Rzymian wyższego stanu. Wysłał do Kartaginy trzy miary (bushle) pierścieni — ponad 200 sztuk — jako dowód skali zwycięstwa. Senat kartagiński był w szoku: nigdy Rzym nie poniósł takiej klęski.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'cannae_map_rare',
    battleId: 'cannae-216bc',
    name: 'Plan Podwójnego Okrążenia',
    category: 'document',
    rarity: 'rare',
    icon: '📜',
    description: 'Schemat manewru Hannibala — studiowany do dziś w akademiach wojskowych.',
    lore: 'Podwójne okrążenie pod Kannami to najsłynniejszy manewr w historii wojskowości. Hannibal celowo osłabił centrum, wciągając Rzymian w wklęsły łuk, a potem zamknął kleszcze kawalerią numidyjską. Clausewitz, Napoleon i Schwarzkopf studiowali ten manewr. Do dziś jest wykładany w West Point i Sandhurst.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'cannae_hannibal_coin',
    battleId: 'cannae-216bc',
    name: 'Moneta Hannibala',
    category: 'personal',
    rarity: 'legendary',
    icon: '🪙',
    description: 'Srebrna moneta Kartaginy z wizerunkiem Hannibala i słonia bojowego.',
    lore: 'Hannibal Barkas — "Błyskawica" — jest uważany za jednego z najwybitniejszych dowódców w historii. Po Kannach stał u bram Rzymu, ale nie zaatakował miasta. "Umiesz zwyciężać, Hannibalu, ale nie umiesz korzystać ze zwycięstwa" — rzekł mu Maharbal. Ta moneta upamiętnia moment, gdy Rzym był najbliżej zagłady.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Kann',
    unlockedBy: 'complete',
    xpReward: 400, coinReward: 150,
  },
];

// ── Artefakty Hastings 1066 ─────────────────────────────
const HASTINGS_ARTIFACTS: Artifact[] = [
  {
    id: 'hastings_axe_common',
    battleId: 'hastings-1066',
    name: 'Topór Huskarla',
    category: 'weapon',
    rarity: 'common',
    icon: '🪓',
    description: 'Dwuręczny topór duński — broń elitarnej gwardii Harolda.',
    lore: 'Huskarle — elitarni wojownicy anglosascy — walczyli dwuręcznymi toporami duńskimi o długości 1,5 metra. Topór mógł przeciąć konia i jeźdźca jednym ciosem. Pod Hastings huskarle tworzyli mur tarczy wokół króla Harolda na wzgórzu Senlac. Ich opór trwał cały dzień.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'hastings_hauberk_uncommon',
    battleId: 'hastings-1066',
    name: 'Kolczuga Normandzka',
    category: 'armor',
    rarity: 'uncommon',
    icon: '🛡',
    description: 'Kolczuga normandzkiego rycerza — sięgała do kolan.',
    lore: 'Normandzcy rycerze nosili hauberki — długie kolczugi z kapturem. Każda składała się z ponad 30 000 nitowanych ogniw żelaznych. Pod Hastings kolczuga chroniła przed ciosami mieczy, ale nie przed toporami huskarli. Tkanina Bayeux przedstawia rycerzy w identycznych kolczugach — standaryzacja wyposażenia na skalę XI wieku.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'hastings_arrow_uncommon',
    battleId: 'hastings-1066',
    name: 'Strzała Normandzka',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '🏹',
    description: 'Strzała, która według legendy zabiła króla Harolda.',
    lore: 'Według tradycji Harold II zginął trafiony strzałą w oko — scena uwieczniona na Tkaninie z Bayeux. Historycy debatują czy to prawda, ale faktem jest że normandzcy łucznicy odegrali kluczową rolę. Wilhelm nakazywał strzelanie nawisowo — strzały spadały na Anglosasów z góry, omijając mur tarczy.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'hastings_tapestry_rare',
    battleId: 'hastings-1066',
    name: 'Fragment Tkaniny z Bayeux',
    category: 'document',
    rarity: 'rare',
    icon: '🧵',
    description: 'Słynna tkanina upamiętniająca podbój Anglii — 70 metrów historii.',
    lore: 'Tkanina z Bayeux — 70 metrów lnu haftowanego w 10 kolorach — to najsłynniejszy "komiks" średniowiecza. Przedstawia 626 postaci, 202 konie, 41 okrętów i wydarzenia od przysięgi Harolda po koronację Wilhelma. Prawdopodobnie wykonana na zlecenie biskupa Odo, przyrodniego brata Wilhelma, w latach 1070-1080.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'hastings_crown_rare',
    battleId: 'hastings-1066',
    name: 'Korona Anglii',
    category: 'personal',
    rarity: 'rare',
    icon: '👑',
    description: 'Symbol władzy — korona przeszła od Harolda do Wilhelma.',
    lore: 'Wilhelm został koronowany w Boże Narodzenie 1066 w Opactwie Westminsterskim. Gdy zgromadzeni wykrzyknęli aklamację, normandzka straż na zewnątrz pomyślała że to zamieszki i podpaliła okoliczne domy. Koronacja odbyła się w dymie i chaosie — proroczo dla panowania, które zmieniło Anglię na zawsze.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'hastings_domesday_book',
    battleId: 'hastings-1066',
    name: 'Księga Domesday',
    category: 'document',
    rarity: 'legendary',
    icon: '📖',
    description: 'Wielki spis Wilhelma Zdobywcy — pierwszy "spis ludności" Anglii.',
    lore: 'W 1086 roku Wilhelm nakazał spisać każdy skrawek ziemi, każde zwierzę i każdego człowieka w Anglii. Księga Domesday ("Dnia Sądu Ostatecznego") to najstarszy publiczny dokument rządowy w historii Anglii. Pokazuje skalę normandzkiego podboju — niemal cała ziemia przeszła w ręce normandzkiej arystokracji.',
    unlockCondition: 'Odwiedź pole bitwy pod Hastings (GPS)',
    unlockedBy: 'visit_gps',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Wiedeń 1683 ───────────────────────────────
const VIENNA_ARTIFACTS: Artifact[] = [
  {
    id: 'vienna_hussar_wing_common',
    battleId: 'vienna-1683',
    name: 'Skrzydło Husarskie',
    category: 'armor',
    rarity: 'common',
    icon: '🪶',
    description: 'Drewniane skrzydło z piórami — symbol polskiej husarii.',
    lore: 'Husarze nosili drewniane skrzydła z piórami orła lub sępa, przymocowane do pleców lub siodła. Pod Wiedniem szum piór i łopot skrzydeł w galopie przerażał konie tureckie. 3 000 husarzy Sobieskiego uderzyło z Kahlenbergu o 18:00 — największa szarża kawalerii w historii.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'vienna_koncerz_uncommon',
    battleId: 'vienna-1683',
    name: 'Koncerz Husarski',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '⚔',
    description: 'Długi, wąski miecz do przebijania zbroi — broń pomocnicza husarii.',
    lore: 'Koncerz — miecz o długości ponad metra, bez ostrza, służący wyłącznie do pchnięć — był bronią husarza po złamaniu kopii. Pod Wiedniem husarze przebijali kolczugi tureckich sipahów jednym pchnięciem. Broń ta była unikalna dla polskiej jazdy — żadna inna armia w Europie jej nie stosowała.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'vienna_turkish_tent_uncommon',
    battleId: 'vienna-1683',
    name: 'Namiot Kara Mustafy',
    category: 'personal',
    rarity: 'uncommon',
    icon: '⛺',
    description: 'Fragment luksusowego namiotu wielkiego wezyra — łup wojenny.',
    lore: 'Kara Mustafa rozłożył pod Wiedniem obóz godny sułtana — z fontannami, dywanami i haremem. Po klęsce Polacy i Austriacy zdobyli ogromne łupy. Sobieski pisał do żony Marysieńki: "Namioty tak bogate, że trudno opisać". Namiot wezyra trafił do Muzeum Historii Sztuki w Wiedniu.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'vienna_sobieski_letter_rare',
    battleId: 'vienna-1683',
    name: 'List do Marysieńki',
    category: 'document',
    rarity: 'rare',
    icon: '📜',
    description: 'Słynny list Sobieskiego do żony: "Bóg i Pan nasz... dał zwycięstwo".',
    lore: '"Bóg i Pan nasz na wieki błogosławiony dał zwycięstwo i sławę narodowi naszemu, o jakiej wieki przeszłe nigdy nie słyszały" — pisał Sobieski do Marysieńki 13 września 1683. List, pełen miłości i dumy, jest jednym z najsłynniejszych dokumentów w historii Polski. Oryginał przechowywany jest w Bibliotece Czartoryskich.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'vienna_coffee_rare',
    battleId: 'vienna-1683',
    name: 'Worki Kawy',
    category: 'personal',
    rarity: 'rare',
    icon: '☕',
    description: 'Zdobyczne worki kawy — początek wiedeńskiej kultury kawowej.',
    lore: 'Według legendy Jerzy Franciszek Kulczycki — polsko-ukraiński szpieg, który przeniknął przez linie tureckie — otrzymał po bitwie zdobyczne worki kawy. Otworzył pierwszą kawiarnię w Wiedniu "Pod Błękitną Butelką". Tak narodziła się słynna wiedeńska kultura kawowa — kawa po wiedeńsku pochodzi z tureckiego łupu.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'vienna_kopia_husarska',
    battleId: 'vienna-1683',
    name: 'Kopia Husarska',
    category: 'weapon',
    rarity: 'legendary',
    icon: '🔱',
    description: 'Pięciometrowa kopia husarska — broń która złamała oblężenie.',
    lore: 'Kopia husarska miała ponad 5 metrów długości i była pusta w środku — lekka, ale śmiertelna. Łamała się przy pierwszym uderzeniu, ale impet szarży z góry Kahlenbergu był nie do zatrzymania. Sobieski osobiście prowadził szarżę — jedyny król w historii nowożytnej, który walczył w pierwszym szeregu. Odwiedź Wiedeń, aby odblokować ten artefakt.',
    unlockCondition: 'Odwiedź pole bitwy pod Wiedniem (GPS)',
    unlockedBy: 'visit_gps',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Rocroi 1643 ───────────────────────────────
const ROCROI_ARTIFACTS: Artifact[] = [
  {
    id: 'rocroi_pike_common',
    battleId: 'rocroi-1643',
    name: 'Pika Tercio',
    category: 'weapon',
    rarity: 'common',
    icon: '🪃',
    description: 'Sześciometrowa pika piechura hiszpańskiego tercio.',
    lore: 'Tercio — formacja 3 000 piechurów z pikami i muszkietami — dominowało na polach bitew Europy przez 150 lat. Pod Rocroi hiszpańskie tercios stanęły murem, odpierając trzy szarże kawalerii francuskiej. Dopiero gdy Condé osobiście poprowadził czwarty atak, formacja pękła.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'rocroi_rapier_uncommon',
    battleId: 'rocroi-1643',
    name: 'Rapier Oficerski',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '⚔',
    description: 'Elegancki rapier francuskiego oficera kawalerii.',
    lore: 'Francuscy oficerowie walczyli rapierami — lekkimi, długimi mieczami do pchnięć. Młody Louis de Bourbon, książę Condé, miał zaledwie 21 lat pod Rocroi. Mimo młodości wykazał geniusz taktyczny — udawał odwrót na prawym skrzydle, by wciągnąć Hiszpanów w pułapkę. Jego rapier stał się symbolem francuskiego zwycięstwa.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'rocroi_morion_uncommon',
    battleId: 'rocroi-1643',
    name: 'Morion Hiszpański',
    category: 'armor',
    rarity: 'uncommon',
    icon: '⛑',
    description: 'Charakterystyczny hełm z grzebieniem — symbol piechoty hiszpańskiej.',
    lore: 'Morion — hełm z wysokim grzebieniem i szerokim rondem — był noszony przez piechurów tercio przez ponad sto lat. Pod Rocroi starzy weterani hiszpańscy w morionach walczyli do końca. Gdy Condé zaproponował im honorową kapitulację, odmówili. Zginęli niemal do ostatniego — koniec epoki niezwyciężonej piechoty.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'rocroi_dispatch_rare',
    battleId: 'rocroi-1643',
    name: 'Depesza Condégo',
    category: 'document',
    rarity: 'rare',
    icon: '📜',
    description: 'Raport z pola bitwy wysłany do regentki Anny Austriaczki.',
    lore: 'Condé wysłał wiadomość o zwycięstwie do Paryża, gdzie regentka Anna Austriaczka rządziła w imieniu 4-letniego Ludwika XIV. Ironia — Anna była Habsburżanką, a Condé pobił armię jej rodziny. To zwycięstwo umocniło pozycję Francji jako dominującej potęgi militarnej Europy na następne 150 lat.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'rocroi_musket_rare',
    battleId: 'rocroi-1643',
    name: 'Muszkiet Lontowy',
    category: 'weapon',
    rarity: 'rare',
    icon: '🔫',
    description: 'Muszkiet z lontem — broń która kończyła epokę rycerstwa.',
    lore: 'Muszkiet lontowy ważył 8 kg i wymagał widełek do strzelania. Pod Rocroi muszkieterzy tercio dawali salwy z odległości 50 metrów — zabójcze, ale wolne w ładowaniu. Między salwami pikarzy musieli chronić muszkieterów. Gdy francuska kawaleria wdarła się w szyki, muszkieterzy byli bezbronni.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'rocroi_conde_baton',
    battleId: 'rocroi-1643',
    name: 'Buława Marszałkowska',
    category: 'personal',
    rarity: 'legendary',
    icon: '🏛',
    description: 'Symbol najwyższej rangi wojskowej — buława marszałka Francji.',
    lore: 'Po Rocroi Condé stał się bohaterem Francji i jednym z najwybitniejszych dowódców XVII wieku. Paradoksalnie, później stanął przeciw królowi we Frondzie i walczył nawet po stronie Hiszpanii. Buława marszałkowska symbolizuje genialność wojskową, która nie zawsze szła w parze z lojalnością polityczną.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Rocroi',
    unlockedBy: 'complete',
    xpReward: 400, coinReward: 150,
  },
];

// ── Artefakty Marna 1914 ────────────────────────────────
const MARNE_ARTIFACTS: Artifact[] = [
  {
    id: 'marne_kepi_common',
    battleId: 'marne-1914',
    name: 'Kepi Piechura',
    category: 'armor',
    rarity: 'common',
    icon: '🎖',
    description: 'Czerwone kepi francuskiego żołnierza — cel idealny dla snajpera.',
    lore: 'W 1914 roku Francuzi szli do wojny w mundurach z 1870 roku — czerwone spodnie, niebieskie kurtki, kepi bez żadnej ochrony. "Le pantalon rouge c\'est la France!" — krzyknął minister wojny, odrzucając mundury polowe. Pod Marną płacili za to krwią — widoczni z kilometra, padali tysiącami.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'marne_taxi_uncommon',
    battleId: 'marne-1914',
    name: 'Model Taksówki Paryskiej',
    category: 'personal',
    rarity: 'uncommon',
    icon: '🚕',
    description: 'Replika słynnej taksówki Renault AG1 — "Taxis de la Marne".',
    lore: 'Gdy Niemcy zbliżali się do Paryża, generał Gallieni zarekwirował 600 paryskich taksówek Renault AG1 i wysłał nimi 6 000 żołnierzy na front nad Marną. Każda taksówka wiozła 5 żołnierzy. To pierwszy w historii transport wojsk pojazdami silnikowymi. "Taxis de la Marne" stały się legendą francuskiego oporu.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'marne_rifle_uncommon',
    battleId: 'marne-1914',
    name: 'Karabin Lebel 1886',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '🔫',
    description: 'Standardowy karabin piechoty francuskiej z 1886 roku.',
    lore: 'Lebel 1886 — pierwszy karabin wojskowy na proch bezdymny — był bronią, z którą Francja weszła w wojnę. Mimo 28-letniego stażu wciąż był niezawodny. Pod Marną 150 000 francuskich żołnierzy z Lebelami zatrzymało niemiecką nawałnicę. Bitwa trwała tydzień — najdłuższy tydzień w historii Francji.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'marne_order_rare',
    battleId: 'marne-1914',
    name: 'Rozkaz Joffre\'a',
    category: 'document',
    rarity: 'rare',
    icon: '📋',
    description: 'Słynny rozkaz generała Joffre\'a: "Żołnierz, który nie może iść naprzód..."',
    lore: '"Żołnierz, który nie może iść naprzód, musi strzec zdobytego terenu za wszelką cenę i dać się zabić na miejscu, zamiast cofnąć się" — rozkaz Joffre\'a z 5 września 1914. Te brutalne słowa zatrzymały odwrót francuskiej armii i odmieniły losy bitwy. Plan Schlieffena upadł nad Marną.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'marne_map_rare',
    battleId: 'marne-1914',
    name: 'Mapa Planu Schlieffena',
    category: 'document',
    rarity: 'rare',
    icon: '🗺',
    description: 'Mapa niemieckiego planu błyskawicznego podboju Francji.',
    lore: 'Plan Schlieffena zakładał zmiażdżenie Francji w 42 dni prawym skrzydłem przez Belgię, a potem obrót na Rosję. Pod Marną Moltke mł. osłabił prawe skrzydło, by wzmocnić lewe — błąd krytyczny. Luka między 1. i 2. Armią niemiecką została wykryta przez lotnictwo zwiadowcze. Francuzi uderzyli w lukę i zmienili bieg historii.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'marne_gallieni_phone',
    battleId: 'marne-1914',
    name: 'Telefon Galliéniego',
    category: 'personal',
    rarity: 'legendary',
    icon: '📞',
    description: 'Telefon polowy gubernatora Paryża — narzędzie które uratowało stolicę.',
    lore: 'Generał Joseph Gallieni — 65-letni gubernator Paryża — jako pierwszy zauważył lukę w niemieckich liniach. Telefonicznie przekonał sceptycznego Joffre\'a do kontrataku. Bez Galliéniego nie byłoby "Cudu nad Marną". Paryż był przygotowany na ewakuację rządu — Gallieni wybrał walkę zamiast ucieczki.',
    unlockCondition: 'Odwiedź pole bitwy nad Marną (GPS)',
    unlockedBy: 'visit_gps',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Normandia 1944 ────────────────────────────
const NORMANDY_ARTIFACTS: Artifact[] = [
  {
    id: 'normandy_dogtag_common',
    battleId: 'normandy-1944',
    name: 'Nieśmiertelnik GI',
    category: 'personal',
    rarity: 'common',
    icon: '🪪',
    description: 'Aluminiowy nieśmiertelnik amerykańskiego żołnierza — dwa blaszki, jedna na ciele, druga w bucie.',
    lore: 'Każdy żołnierz aliancki nosił dwa dog tags — jeden zostawał z ciałem, drugi zabierany do ewidencji. 6 czerwca 1944 roku fale Kanału wyrzuciły na plaże tysiące blaszek. Na plaży Omaha w pierwszych godzinach poległo 2 000 Amerykanów. Cmentarz w Colleville-sur-Mer przechowuje 9 387 białych krzyży.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'normandy_m1_garand_uncommon',
    battleId: 'normandy-1944',
    name: 'Karabin M1 Garand',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '🔫',
    description: 'Karabin samopowtarzalny — "najlepsza broń kiedykolwiek wymyślona" wg Pattona.',
    lore: 'M1 Garand był pierwszym karabinem samopowtarzalnym przyjętym jako standardowa broń piechoty. Jego charakterystyczny metaliczny "ping" po wystrzeleniu ostatniego naboju ostrzegał żołnierza o pustym magazynku — ale też wroga. Pod Normandią GI z Garandem mógł strzelać dwa razy szybciej niż Niemiec z Karem 98k.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'normandy_paratrooper_uncommon',
    battleId: 'normandy-1944',
    name: 'Spadochron T-5',
    category: 'armor',
    rarity: 'uncommon',
    icon: '🪂',
    description: 'Spadochron desantowy — 13 000 spadochroniarzy skoczyło w noc D-Day.',
    lore: 'W nocy z 5 na 6 czerwca 13 000 amerykańskich i 7 000 brytyjskich spadochroniarzy skoczyło za linie wroga. Wielu wylądowało w bagnach lub na drzewach. Prywatny John Steele z 82. Dywizji Powietrznodesantowej zawisł na wieży kościoła w Sainte-Mère-Église — scena uwieczniona w filmie "Najdłuższy dzień".',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'normandy_ike_order_rare',
    battleId: 'normandy-1944',
    name: 'Rozkaz Dnia Eisenhowera',
    category: 'document',
    rarity: 'rare',
    icon: '📋',
    description: 'Słynny rozkaz "You are about to embark upon the Great Crusade".',
    lore: '"Żołnierze, marynarze i lotnicy Sił Ekspedycyjnych Aliantów! Wyruszacie na Wielką Krucjatę" — pisał Eisenhower 6 czerwca. Miał też w kieszeni drugą wiadomość — na wypadek klęski: "Desant się nie powiódł. Wycofuję wojska. Wina jest wyłącznie moja". Nigdy nie musiał jej użyć.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'normandy_czech_hedgehog_rare',
    battleId: 'normandy-1944',
    name: 'Jeż Czeski',
    category: 'weapon',
    rarity: 'rare',
    icon: '⚙',
    description: 'Stalowa zapora plażowa — element Wału Atlantyckiego Rommla.',
    lore: 'Rommel osobiście nadzorował budowę Wału Atlantyckiego — miliony min, betonowych bunkrów i stalowych "jeży czeskich" na plażach. Jeże miały rozpruwać kadłuby barek desantowych. Pod Omaha Beach jeże zatrzymały wiele jednostek — żołnierze musieli biec 300 metrów plaży pod krzyżowym ogniem. Straty na Omaha sięgnęły 90% w niektórych kompaniach.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'normandy_cricket_clicker',
    battleId: 'normandy-1944',
    name: 'Świerszcz Spadochroniarza',
    category: 'personal',
    rarity: 'legendary',
    icon: '🦗',
    description: 'Blaszany "cricket" — klik-klak do rozpoznawania swoich w ciemności.',
    lore: 'Spadochroniarze 101. Dywizji Powietrznodesantowej otrzymali małe blaszane "świerszcze" — jedno kliknięcie pytało "swój?", dwa kliknięcia odpowiadały "swój!". W ciemności normandzkiej nocy, rozrzuceni po bagnach i polach, żołnierze odnajdywali się po dźwięku tego prostego urządzenia. Cricket uratował setki żyć.',
    unlockCondition: 'Odwiedź plaże Normandii (GPS)',
    unlockedBy: 'visit_gps',
    xpReward: 350, coinReward: 120,
  },
];

// ── Artefakty Berlin 1945 ───────────────────────────────
const BERLIN_ARTIFACTS: Artifact[] = [
  {
    id: 'berlin_ppsh_common',
    battleId: 'berlin-1945',
    name: 'PPSz-41',
    category: 'weapon',
    rarity: 'common',
    icon: '🔫',
    description: 'Sowiecki pistolet maszynowy — broń walki ulicznej w Berlinie.',
    lore: 'PPSz-41 z charakterystycznym bębnowym magazynkiem na 71 naboi był idealny do walki w ruinach Berlina. Radziecki żołnierz z PPSz — "papaszą" — stał się symbolem zwycięstwa. W maju 1945 ponad 2,5 miliona żołnierzy radzieckich szturmowało Berlin, wielu uzbrojonych właśnie w tę broń.',
    unlockCondition: 'Odsłuchaj dowolną narrację',
    unlockedBy: 'listen',
    xpReward: 25, coinReward: 10,
  },
  {
    id: 'berlin_panzerfaust_uncommon',
    battleId: 'berlin-1945',
    name: 'Panzerfaust',
    category: 'weapon',
    rarity: 'uncommon',
    icon: '💥',
    description: 'Jednorazowy granatnik przeciwpancerny — ostatnia broń Volkssturmu.',
    lore: 'W ostatnich dniach Rzeszy nawet starcy i dzieci z Volkssturmu otrzymywali Panzerfausty — proste, jednorazowe granatniki. Panzerfaust mógł zniszczyć T-34 z 30 metrów, ale wymagał desperackiej odwagi. W ruinach Berlina Hitlerjugend — chłopcy w wieku 14-16 lat — strzelali z Panzerfaustów do radzieckich czołgów.',
    unlockCondition: 'Odsłuchaj narrację Strony A',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'berlin_red_flag_uncommon',
    battleId: 'berlin-1945',
    name: 'Czerwony Sztandar',
    category: 'personal',
    rarity: 'uncommon',
    icon: '🚩',
    description: 'Flaga sowiecka wbita na Reichstagu — symbol końca wojny.',
    lore: 'Słynne zdjęcie Jewgienija Chałdieja — "Sztandar Zwycięstwa nad Reichstagiem" — zostało inscenizowane 2 maja 1945. Ale prawdziwi żołnierze — Kantarija i Jegorow — wbili sztandar na dachu Reichstagu w nocy z 30 kwietnia na 1 maja. Zginęło przy tym wielu. Walka o Reichstag kosztowała 2 000 ofiar po obu stronach.',
    unlockCondition: 'Odsłuchaj narrację Strony B',
    unlockedBy: 'listen',
    xpReward: 50, coinReward: 20,
  },
  {
    id: 'berlin_kapitulation_rare',
    battleId: 'berlin-1945',
    name: 'Akt Bezwarunkowej Kapitulacji',
    category: 'document',
    rarity: 'rare',
    icon: '📜',
    description: 'Dokument kończący wojnę w Europie — podpisany 8 maja 1945.',
    lore: 'Generałpułkownik Alfred Jodl podpisał akt kapitulacji w Reims 7 maja, ale Stalin zażądał powtórzenia ceremonii w Berlinie-Karlshorst. 8 maja (9 maja czasu moskiewskiego) Wilhelm Keitel podpisał bezwarunkową kapitulację przed Żukowem. Dlatego Zachód świętuje 8 maja, a Rosja — 9 maja.',
    unlockCondition: 'Odsłuchaj wszystkie perspektywy',
    unlockedBy: 'listen_all',
    xpReward: 100, coinReward: 40,
  },
  {
    id: 'berlin_iron_cross_rare',
    battleId: 'berlin-1945',
    name: 'Krzyż Żelazny',
    category: 'personal',
    rarity: 'rare',
    icon: '✙',
    description: 'Odznaczenie wojskowe — masowo przyznawane w ostatnich dniach Rzeszy.',
    lore: 'W ostatnich tygodniach wojny Hitler szafował Krzyżami Żelaznymi — przyznawał je nawet 12-latkom z Hitlerjugend, którzy zniszczyli radziecki czołg. To była propaganda rozpaczy. 20 kwietnia 1945, w swoje ostatnie urodziny, Hitler odznaczył grupę chłopców z HJ w ogrodzie kancelarii Rzeszy — jedno z ostatnich zdjęć Führera.',
    unlockCondition: 'Odsłuchaj narrację Narratora',
    unlockedBy: 'listen',
    xpReward: 75, coinReward: 30,
  },
  {
    id: 'berlin_reichstag_stone',
    battleId: 'berlin-1945',
    name: 'Kamień z Reichstagu',
    category: 'personal',
    rarity: 'legendary',
    icon: '🏛',
    description: 'Fragment ściany Reichstagu z napisami zwycięskich żołnierzy.',
    lore: 'Po zdobyciu Reichstagu tysiące radzieckich żołnierzy wyryło swoje imiona na ścianach budynku — "Дошёл до Берлина!" (Dotarłem do Berlina!). Napisy zachowano podczas renowacji w latach 90. — widoczne do dziś w korytarzach Bundestagu. To grafitti zwycięzców — surowy, osobisty pomnik końca wojny.',
    unlockCondition: 'Ukończ wszystkie aktywności dla Berlina',
    unlockedBy: 'complete',
    xpReward: 400, coinReward: 150,
  },
];

// ── Eksport wszystkich artefaktów ─────────────────────────
export const ALL_ARTIFACTS: Artifact[] = [
  ...GRUNWALD_ARTIFACTS,
  ...YPRES_ARTIFACTS,
  ...WATERLOO_ARTIFACTS,
  ...VERDUN_ARTIFACTS,
  ...THERMOPYLAE_ARTIFACTS,
  ...AGINCOURT_ARTIFACTS,
  ...BORODINO_ARTIFACTS,
  ...GETTYSBURG_ARTIFACTS,
  ...BRITAIN_ARTIFACTS,
  ...STALINGRAD_ARTIFACTS,
  ...MARATHON_ARTIFACTS,
  ...LEPANTO_ARTIFACTS,
  ...AUSTERLITZ_ARTIFACTS,
  ...SOMME_ARTIFACTS,
  ...KURSK_ARTIFACTS,
  ...CANNAE_ARTIFACTS,
  ...HASTINGS_ARTIFACTS,
  ...VIENNA_ARTIFACTS,
  ...ROCROI_ARTIFACTS,
  ...MARNE_ARTIFACTS,
  ...NORMANDY_ARTIFACTS,
  ...BERLIN_ARTIFACTS,
];

// ── Helper: artefakty dla bitwy ──────────────────────────
export function getArtifactsForBattle(battleId: string): Artifact[] {
  return ALL_ARTIFACTS.filter(a => a.battleId === battleId);
}

// ── Helper: statystyki kolekcji ──────────────────────────
export function getCollectionStats(unlockedIds: string[]) {
  const total    = ALL_ARTIFACTS.length;
  const unlocked = unlockedIds.length;
  const byRarity = {
    common:    ALL_ARTIFACTS.filter(a => a.rarity === 'common'    && unlockedIds.includes(a.id)).length,
    uncommon:  ALL_ARTIFACTS.filter(a => a.rarity === 'uncommon'  && unlockedIds.includes(a.id)).length,
    rare:      ALL_ARTIFACTS.filter(a => a.rarity === 'rare'      && unlockedIds.includes(a.id)).length,
    legendary: ALL_ARTIFACTS.filter(a => a.rarity === 'legendary' && unlockedIds.includes(a.id)).length,
  };
  return { total, unlocked, byRarity, pct: Math.round((unlocked / total) * 100) };
}
